name: customer_grocery
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  bloc: null
  bloc_concurrency: ^0.2.2
  bloc_provider: null
  cached_network_image: null
  dartz: ^0.10.1
  dio: ^5.3.2
  logger: ^2.0.2
  flutter:
    sdk: flutter
  flutter_bloc: null
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_slidable: ^3.0.0
  freezed_annotation: null
  get_it: ^7.6.4
  go_router: ^10.1.2
  intl: null
  json_annotation: null
  shared_preferences: ^2.2.0
  shimmer: ^3.0.0
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  hive:
  tot_atomic_design:
    git:
      url: https://github.com/TOTPLATFORM/flutter-atoms.git
      path: packages/tot_atomic_design
      ref: dev

dev_dependencies:
  build_runner: null
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  freezed: null
  json_serializable: null
  hive_generator:

flutter:
  uses-material-design: true
